[geany]
pref_main_load_session=false
pref_main_project_session=false
pref_editor_default_new_encoding=UTF-8
default_open_path=
cmdline_new_files=true
notebook_double_click_hides_widgets=false
tab_pos_editor=2
tab_pos_msgwin=2
sidebar_pos=0
symbols_sort_mode=0
msgwin_orientation=1
highlighting_invert_all=false
pref_main_search_use_current_word=true
check_detect_indent=false
detect_indent_width=false
use_tab_to_indent=true
pref_editor_tab_width=4
indent_mode=2
indent_type=0
virtualspace=1
autocomplete_doc_words=false
completion_drops_rest_of_word=false
color_scheme=tangram.conf

[tools]
terminal_cmd=lxterminal
browser_cmd=dillo
grep_cmd=grep
