profile=gpu-hq
vo=gpu
hwdec=auto-safe
osc=yes
osd-bar=yes
osd-font=Sans
osd-font-size=24
osd-color=#FFFFFFFF
osd-border-color=#DB0085FF
osd-back-color=#111318CC
osd-shadow-color=#111318FF
term-osd-bar=yes
force-window=immediate
idle=yes
